### ISSUE TITLE
Project Group

### ISSUE THREAD

**Issue by initseis** [the-catalystmc/space-travelers-hub#46]
Project: https://github.com/the-catalystmc/space-travelers-hub/projects/1
This group has two member:
- @sevinchek 
- @the-catalystmc

**Comment by Davidosky007** [comment]
## Hi @sevinchek @the-catalystmc 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 
![thank-you-cr-gif](https://user-images.githubusercontent.com/52497246/131380481-d734ca2c-a236-4f8f-a79c-3c69cd0c3fd6.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
